
version: '2.1'
services:
  rabbitmq-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${SERVICES_CLOUDBUS_DOMAIN:-cloudbus}.${INFRASTRUCTURE:-local}
    hostname: ${SERVICES_CLOUDBUS_DOMAIN:-cloudbus}.${INFRASTRUCTURE:-local}
    image: ${DOCKER_REGISTRY:-home1oss}/rabbitmq:3.6.5-management
    ports:
    - "15672:15672"
    #- "25672:25672"
    #- "4369:4369"
    #- "5671:5671"
    - "5672:5672"
    environment:
    - RABBITMQ_DEFAULT_USER=${SPRING_RABBITMQ_USERNAME:-user}
    - RABBITMQ_DEFAULT_PASS=${SPRING_RABBITMQ_PASSWORD:-user_pass}
    - RABBITMQ_HIPE_COMPILE=0
    volumes:
    - volume-rabbitmq-management:/var/lib/rabbitmq

volumes:
  volume-rabbitmq-management: {}

networks:
  default:
    external:
      name: oss-network
